apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-service
  namespace: sample-crud
spec:
  type: ClusterIP
  selector:
    app: nginx-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
