apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: sample-crud
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: sample_crud
      owner: sampleuser
      secret:
        name: postgres-app-user

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
